### ISSUE TITLE
Implement Instructions for WSL2

### ISSUE THREAD

**Issue by xandora** [TheOdinProject/top-meta#141]
| Title | Author | Date |
| --- | --- | --- |
| Implement Instructions for WSL2 | `Michael Frank` | 2022/03/18 |

# Implement Instructions for WSL2

## Summary

After a discussion between maintainers, it was decreed that an issue be drafted for the inclusion of WSL2 among the supported systems.

## Motivation

With the increasing prevelance of Windows 11 and the apparent slow progress by Oracle to validate it as a support host for VirtualBox VMs, an alternative solution should be available for users that are uncomfortable with dual-booting.

## Suggested implementation

- Follow [Microsoft guideline](https://docs.microsoft.com/en-us/windows/wsl/install) on installing WSL2
- Expect that learners stick with the default distribution (Ubuntu)
- Install Windows Terminal:
    - Creating a quicklaunch shortcut
- Install VSCode:
    - WSL-remote extensions
- Install Required Tools:
    - Node.js
    - Ruby
- Create a series of "How-to" guides to for non-obvious operations:
    - "Importing" resources to WSL environment
    - GUI Applications
    - Interactions and pitfalls between WSL2 and Windows functionality

## Drawbacks

- There is the potential for numerous questions regarding the confusing interactions with how the Linux Subsystem works with Windows Explorer and file saving.

**Comment by crespire** [comment]
I'd like to volunteer to generate a first draft of this if it's still on the table.

**Comment by xandora** [comment]
@crespire As per the FAQ in the readme of this repository, the issues here are things the core/maintainer team are either considering or planning to take on internally.

This particular issue is not as critical as it was when it was originally posted, VirtualBox is very stable on Windows 11 now and we still haven't *really* had the discussion about wanting to support WSL officially.

**Comment by Asartea** [comment]
I just saw that this exists, and I think this should have been completed when we implemented WSL instructions a month or so ago?

**Comment by xandora** [comment]
Yep, this can probably be closed off now.
