### ISSUE TITLE
Feature: add Firebase lessons

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#170]
## Summary

Two new Firebase lessons that cover how to setup Firebase, authentication and Firestore.

## Motivation

Currently, we link to [Google Codelab](https://firebase.google.com/codelabs/firebase-web#0) in the [Using BaaS for your backend lesson](https://www.theodinproject.com/lessons/javascript-using-baas-for-your-back-end) to impart necessary Firebase knowledge to complete the Where's Waldo and the JavaScript final project. I believe the codelab follows a "copy paste" approach and is not effective in teaching Firebase utilities. It also covers tools like Notifications and Performance Data which is beyond the scope of the curriculum.

We need concise lessons to cover everything a user will need from Firebase to complete the two aforementioned projects.

## Suggested implementation

Replace the current [Using BaaS For Your Backend lesson in the NodeJS path](https://www.theodinproject.com/lessons/javascript-using-baas-for-your-back-end) with these two lessons: 

### 1. Getting Started with Firebase

This lesson should cover:

- [ ] Why we need Firebase
- [ ] How to setup a Firebase project on Firebase's web console
- [ ] How to setup a project to use Firebase
- [ ] How to setup user authentication using Firebase
- [ ] How to deploy the app on Firebase Hosting

### 2. Using the Firestore Database

This lesson should cover:

- [ ] CRUD (with code examples)
  - [ ] How to query Firestore
- [ ] How to setup a snapshot listener (with example)
- [ ] How to configure Firestore security rules
- [ ] How to structure/model data (a very brief section)

## Drawbacks

None, really. Though it can be debated if the above lessons are mandatory additions to the curriculum.

## Alternatives

Not adding the above two lessons at all.

**Comment by I3uckwheat** [comment]
I have some concerns about this being worth doing.. 

Due to the fact that Firebase was a stand-in for a backend and isn't something we really care about past that. This *could* change if we wanted it to however, but as it stands that is the history around it. We first have to decide if we *want* to go down this path and if it's a good idea over having people learn how to use something through documentation.

**Comment by 01zulfi** [comment]
Closing since discussion obsolete with the new React course
