### ISSUE TITLE
Section: Introduction

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#195]
#### Section Summary

1. Explain how the course will work i.e the course is divided into sections and projects interspersed (similar to other courses).
2. If possible, explain how the structure of lessons i.e a lesson would contain a fair amount of reading and an assignment section for the learners to complete. Briefly mention that the lessons will have a codesandbox embed/practice exercises.
3. Introduce React and its purpose. Briefly go into its significance in front end development. Link to surveys etc to demonstrate its market share against other frameworks. Finally, defend our decision on why we are covering React (in the curriculum) in favour of other libraries/frameworks.
4. Briefly narrate React’s history and their transition from class-based components to functional components. Mention that this course will focus mostly on functional components.
5. Provide instructions for toolings that might be necessary for learners to create their own React environment locally. 

#### Section Lessons

1. How This Course Will Work
2. Introduction To React
3. Setting up a React environment

**Comment by thatblindgeye** [comment]
1. Agreed. A quick rundown of "this course will cover several React concepts. First you'll learn... Then... Finally, the course wraps up with..." is definitely good for each course.
2. We don't really need this part in an intro. Maybe a quick mention of "Throughout the course you'll also be tasked with solving various React based exercises" or something, but we don't need to remind users how the lessons work.
3. Agreed
4. Agreed, though may depend on the execution of functional and class components in the grand scheme of this new course
5. Agreed

Compared to the current "React Introduction" lesson, I think this would be a great improvement to separate things out a bit more and make it more easily consumable.

**Comment by justEstif** [comment]
Section summary: 

- I agree with all the points.

Section lessons: 

- I noticed that the section introduction mentions going "Briefly go into its significance in front end development."
    - The wording is a bit unclear on how this would relate it to the Back-end & React section.
