### ISSUE TITLE
Section: Getting Started With React

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#196]
#### Section Summary

1. Explain that User Interfaces (UI) can be broken down into reusable chunks (components), this is where React shines
2. Have a simple walkthrough where learners are required to set up a project with Create React App and write their first component. This is so that they can get a feel for components and React as a whole. Before we get into any “React”, having code in their text editors is essential so that they can quickly experiment what they learn throughout the lessons.
3. Briefly go over a component’s structure: their names should be capitalised, they return JSX, and they normally live in their own dedicated files. Touch on how to import/export components (components normally get exported as defaults).
4. Explain JSX i.e it is a syntax extension for JavaScript that basically allows writing HTML like code in JavaScript. Prompt learners to console.log JSX elements to show that JSX compiles down to React. Make a case that JSX isn’t required to write React components, although it simplifies the process.
5. Touch on basic syntax for JSX to allow learners to get familiar with JSX. This should allow them to understand any JSX code snippet that comes up in later lessons.
6. With the learner’s newfound power to manipulate JSX, deep dive into some rendering techniques they’ll be using the most. Cover conditional rendering and array rendering with examples and various use cases. This should naturally bring up the key attribute in React. Explain the significance of keys to React. Learners should be able to effectively utilise keys in their code.
7. Explain how data transfers throughout a React application i.e via props. It is one directional data flow meaning data can be passed only from parent to child components. Show props in action with code examples.

#### Section Lessons

1. React Components
2. What is JSX?
3. Rendering Techniques
4. The Key To React
5. Passing Data Between Components

**Comment by thatblindgeye** [comment]
Section Summary
1 - 5: Looks good and like it's essentially our current "React Introduction" lesson split apart, which should allow for more easily digestible material + a chance to provide a little more per topic.

6: Also looks good. Could be a nice place to keep the current exercise for users to create a mini to-do list from [Handle Inputs and Render Lists](https://www.theodinproject.com/lessons/node-path-javascript-handle-inputs-and-render-lists)

Section Lessons
4. Not a blocker, but just "Keys in React" as a lesson title for an alternative
5. Not a blocker either, but could also just name the lesson "Props", but I can see how what you listed might be more helpful to new users to understand what the lesson is about more immediately
