### ISSUE TITLE
Section: Class Components

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#198]
#### Section Summary 

1. Describe the structure of a class based component i.e how to define a class based component, the purpose of the constructor method, the purpose of the render method etc
2. Give a brief overview of how to pass in props and handle state.
3. Explain the significance of `this` in the component and example of how to bind `this` correctly.
4. From the previous sections, the learner should have an idea of a component’s lifecycle even if it isn’t covered explicitly. In class based components, there are special methods called lifecycle methods. Give a brief overview of the important few and allow learners to research on their own. 

#### Section Lessons

1. Class Based Components
2. Component Lifecycle Methods

**Comment by thatblindgeye** [comment]
🔥 

For the most part this looks great. I think *maybe* another lesson or two to separate things out a bit more could work, but I would agree overall with the idea of focusing on functional components, then bringing up class components in a "Functional component do it this way, and here's how it's done with classes" way.

Not entirely sure if I'd personally like to see a full on project here, but at the very least I think instructing users at the end of this section to go back to X project and refactor it to use class based components (similar to the [JavaScript Classes lesson](https://www.theodinproject.com/lessons/node-path-javascript-classes)) would be a good idea for that actual hands-on practice.

**Comment by 01zulfi** [comment]
Great, the lesson count is arbitrary, and we can definitely add more lessons if need be. 

Additionally, completely on board with asking users to refactor an earlier project to class based components.

**Comment by thatblindgeye** [comment]
Yeah the lesson count can definitely change as things start getting written, since it can be difficult to accurately predict just how much content there'll be to write up on.

**Comment by 01zulfi** [comment]
Completed as #230 #231 are resolved
