### ISSUE TITLE
Section: React Testing

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#199]
#### Section Summary

1. Instruct learners to set up their testing files (assuming they will be using CRA). This will have a brief overview of what packages they’ll need to import to get up and running. Focus will be on the React Testing Library.
2. Explain how to query for elements in tests, the types of queries, and the best practices associated with it. 
3. Explain how to simulate user behaviour i.e mouse inputs, keyboard inputs etc in tests via the userEvent API.
4. Describe the concept of Snapshot Testing, and how to perform these tests. Go into the pros and cons of snapshots.
In certain cases, mocks need to happen. Show learners how to mock callback handlers and child components. Use a RTL test suite from The Odin Project’s website (or any other codebase) to showcase a testing example.
5. Explain how to deal with asynchronous code in testing React components. Dive into a use case such as performing a fetch call and conditionally render elements. This could be done with a simple example. 

#### Section Lessons

1. Querying, Simulating, Snapshots
2. Mocking Callbacks And Components
3. Asynchronous Code In React Testing
4. Project: Shopping Cart

**Comment by thatblindgeye** [comment]
Think the only comment I have is for the first lesson, I feel like that should be broken into separate lessons rather than stuffing three concepts into one. Maybe something more along the lines of:

1. Setting up React test files
2. Queries
3. Simulating user events
4. Snapshots
5. Asynchronous code in React testing
6. Project: Shopping Cart

**Comment by 01zulfi** [comment]
The individual lessons might be too short. I was planning to rename and review the current [React Testing Part 1 lesson](https://www.theodinproject.com/lessons/node-path-javascript-react-testing-part-1) to "Querying, Simulating, Snapshots". That lesson should suffice. Although, I see where you're coming from by separating lessons based on concepts. I"ll rethink the lessons when I come around to creating lesson issues for this section.


Question: Looks like your missing the "Mocking Callbacks And Components" in your lesson list?

Good call out on the Shopping Cart project. It definitely needs to be moved in The React Ecosystem section (ideally near the React Router lesson)

**Comment by nevz9** [comment]
In the [React Testing Part 1 lesson](https://www.theodinproject.com/lessons/node-path-javascript-react-testing-part-1) "Simulating User Events". I'm thinking of using a form element with inputs and buttons for demonstration. Then on the [React Testing Part 2 lesson](https://www.theodinproject.com/lessons/node-path-javascript-react-testing-part-2) using the form component demonstrated in the previous lesson, we introduce an api call, that we can mock. It is more robust that flows well with the previous lesson.This is kind of a highly asked question from what I'm seeing.  

Although it does not seem to align with "Mocking Callbacks And Components". Is it something that's gonna be added in this new lesson "Asynchronous code in React testing" instead? Just want to be sure.

**Comment by 01zulfi** [comment]
I like the idea of having the form component example that flows into the next lesson.

> Although it does not seem to align with "Mocking Callbacks And Components". Is it something that's gonna be added in this new lesson "Asynchronous code in React testing" instead? Just want to be sure.

This content is already covered in the [React Testing Part 2 lesson](https://www.theodinproject.com/lessons/node-path-javascript-react-testing-part-2#what-is-mocking)

**Comment by crespire** [comment]
I know this is the TOP meta board, but I believe that any React testing content should also cover end-to-end testing using a browser based runner.

This resource actually seems to take users step by step through such an exercise. A quick review suggests that it might be worth including somehow.

My personal thought is to include it in a "Go do this resource" lesson at the end, as, in my view, e2e testing is an important element of React testing in general.

https://learntdd.in/react/

My experience with this was informed by coming from Rails and having already done Capybara system tests, and I wanted to test my React the same way, and found using `jest-dom` quite limiting, and wished the curriculum covered some e2e testing with a browser based runner.

**Comment by 01zulfi** [comment]
@crespire Thanks for the suggestion.

React testing can be harder to grasp alone and I believe adding e2e testing into the mix would complicate things for new learners. Furthermore, improving our current testing lessons is a priority over covering a new type of testing. I'm not opposed to covering e2e in some capacity, maybe a post Odin course of sorts? Not sure.
