### ISSUE TITLE
Lesson: Foundations - Inspecting HTML and CSS

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/top-meta#20]
# Lesson Overview
This doesn't have to go too far in depth, but knowing how to use the inspector is going to be _crucial_ for the positioning lessons that come up next.

# Lesson Outline
The _order_ of this outline doesn't need to be followed 100%, but the items listed here _do_ need to show up in the lesson somewhere. If you feel like there has been an omission ask in Discord before expanding the scope of this lesson.

- How to access the inspector
- Select and inspect specific elements
- try out styles in the browser
- tips/tricks

# Acceptance Criteria
This is the definition of success. If the requirements here are not met, the work effort is not complete.
- [ ] All items from the outline above are present in the lesson.
- [ ] Lesson follows proper format
  - [ ] Section headings are `###`
  - [ ] Code blocks use `~~~` and include a language name.
  - [ ] Lists are numbered.
- [ ] Lesson has the following sections:
  - [ ] 'Learning Outcomes' at the beginning, optionally after a short introduction paragraph (relatively brief, give students an overview of what they're about to learn, with few specific details)
  - [ ] Assignment(optional) a list of resources to consume.
  - [ ] Practice(optional) 
  - [ ] 'Additional Resources' (should exist even if it's blank)
  - [ ] 'Knowledge Check' (specific questions to test knowledge. Has details. Doesn't just parrot the Learning Outcomes. More of a spot-check, doesn't need to be exhaustive)
- [ ] Lesson has been run through a spell-checker

**Comment by twalton83** [comment]
I'm happy to take this on, given that I'm a major advocate of debugging.

**Comment by codyloyd** [comment]
@twalton83 YOU GOT IT.  Move it to 'in progress' on the project board when you start work.
