### ISSUE TITLE
Section: The React Ecosystem

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#200]
#### Section Summary

1. This section will introduce a handful of useful React libraries and make mention of more which we can’t possibly cover.
Remind learners that React is JavaScript, hence type-checking is still a pain. But fear not, the prop-types library brings some consolation. Give an example of the usage of Component.propTypes and Component.defaultProps. Mention TypeScript as an alternative that allows to type-check the whole application and more.
2. Delve into the rise of client-side routing with SPAs. Introduce React Router as an excellent solution for React. Walkthrough how to incorporate React Router in an application i.e go through Browser Router, Routes, Route etc. Briefly mention features like the Link component, useNavigate etc.
3. Explain how to fetch in React: define a function and invoking it  in useEffect and all that. Explain how to use a Loading component whilst the app is fetching. Introduce the React Query as a solution for efficient fetching in React. Possibly go into some examples.
4. Explore strategies on how to style React applications. Learners could just use vanilla CSS (inline or separate files) or CSS modules. For extended functionality, present Styled Components and perks it provides. Mention full blown component libraries like Chakra UI and Material UI.

#### Section Lessons

1. Type Checking With Prop Types
2. React Router
3. Fetching Data In React
4. Styling React Applications
5. Project: Where’s Waldo

**Comment by thatblindgeye** [comment]
If we plan on introducing TypeScript in the curriculum at some point, then I don't think we need to introduce prop types here. For now I'd be good with it since I don't believe there's any concrete plan for TS.

I updated my comment in the Testing section overview, but I think React Router is being brought in a bit late (or Shopping Cart is brought in a bit early). That project I think really benefits from using React Router.

Otherwise I think whether the backend section is going to be included (and how) might affect this section since it ends with the Waldo project. Do we know how we want to tackle that with the issue of Firebase?

**Comment by 01zulfi** [comment]
> If we plan on introducing TypeScript in the curriculum at some point, then I don't think we need to introduce prop types here. For now I'd be good with it since I don't believe there's any concrete plan for TS.

When I was conceptualizing the course couple months back, I wanted an entire "TypeScript & React" section on there. I decided against it, because I felt the course was getting a bit too loaded (and ambitious). 

> I updated my comment in the Testing section overview, but I think React Router is being brought in a bit late (or Shopping Cart is brought in a bit early). That project I think really benefits from using React Router.

Agreed.

> I think we should also be careful to not introduce too many libraries for users to utilize (mentioning them off-hand or as an additional resource is fine). If there's something that they need a library for (like routing), definitely, but we should consider it's usefulness and whether it wouldn't fit better in a conclusion sort of lesson of "here's some libraries you may/can use for concepts that you've learned about in this course" or something.

I have to think more on this. I plan on The React Ecosystem to be a section where we, as the title suggests, explore the React ecosystem and discuss/mention what solutions React community has built. For example, the router lesson should mention [React Location](https://react-location.tanstack.com/), but officially recommend React Router as that is what we'll support in our (Discord) community. 

> Otherwise I think whether the backend section is going to be included (and how) might affect this section since it ends with the Waldo project. Do we know how we want to tackle that with the issue of Firebase?

Another great call out. Where's Waldo will be removed from here and placed in the backend section. Regarding Firebase, I'm still not sure, Any discussion we start on it ultimately withers out. Nonetheless, as a default, I will be using Firebase in the backend section, unless someone comes up with a better way to tackle this problem.
