### ISSUE TITLE
React Revamp: Course Objectives

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#203]
Learners should be able to:
1. Understand what React is
2. Express UI’s in terms of reusable components
3. Understand JSX and how to effectively use it
4. Pass data b/w components
5. Understand state and:
   - How to set and update state variables
   - How to choose a state variable
   - That React updates UI based off of state
6. Understand the importance of pure React components
7. Understand side effects and where best to handle them
8. Effectively use useEffect
9. Test React components with RTL
10. Recall popular React libraries and their use cases
    -  Types in React
    - Routing in React
    - Querying in React
    - CSS in React
11. Understand contexts and reducers
12. Know about different hooks, their use cases, and how to create a custom hook
13. Apply the above knowledge in projects throughout the course

**Comment by JJJ4032002** [comment]
I think a small section in one of the lessons about debugging react should be added. Or a whole lesson. But i don't think there is enough content for it.
