### ISSUE TITLE
Lesson: Introduction To React

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#220]
## Lesson: Introduction To React

**Section: Introduction**

Related to #195 

----

## Lesson Overview

An introductory lesson on React, its history and why we have chosen to cover React in our curriculum 

## Lesson Outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Introduce React and its purpose. Briefly go into its significance in front end development. Link to surveys etc to demonstrate its market share against other frameworks. Finally, defend our decision on why we are covering React (in the curriculum) in favour of other libraries/frameworks.
- Briefly narrate React’s history and their transition from class-based components to functional components. Mention that this course will focus mostly on functional components but still cover necessary knowledge on class based components.

## Acceptance Criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get The Lesson Template

Download the lesson template using the following command (replace lesson_name with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

### Adding Interactive Examples

We'll use [CodeSandbox](https://codesandbox.io/dashboard) for interactive examples. To add these examples, follow the instructions in the [react-examples](https://github.com/TheOdinProject/react-examples) repository and create a Pull Request there. When approved, the example will eventually be uploaded to CodeSandbox. In the meantime, leave a placeholder in the lesson file like so:

```
// some lesson content

**EXAMPLE GOES HERE**

// some lesson content

```

**Comment by aaronlrv** [comment]
Hey i'd like to work on this

**Comment by 01zulfi** [comment]
Completed with https://github.com/TheOdinProject/curriculum/pull/24636
