### ISSUE TITLE
Lesson: Setting Up A React Environment

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#221]
## Lesson: Setting Up A React Environment

**Section: Introduction**

Related to #195 

----

## Lesson Overview

Guidance on tools to set up a local React env

## Lesson Outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Mention that you can set up a React project from scratch but that will cause a lot of headaches
- Mention that there are many tools available to scaffold a React app (CRA, vite's react config, etc etc)
- Mention that we'll be using CRA since it's beginner friendly
- Guide through the CLI instructions using CRA and briefly explain the project structure
- Mention that CRA comes with ESLint under the hood and advise learners to set up Prettier if they want to
- Provide link to the React Developer Tool's Chrome extension and briefly explain its usefulness
- Provide a resource for React Developer Tool

## Acceptance Criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get The Lesson Template

Download the lesson template using the following command (replace lesson_name with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

### Adding Interactive Examples

We'll use [CodeSandbox](https://codesandbox.io/dashboard) for interactive examples. To add these examples, follow the instructions in the [react-examples](https://github.com/TheOdinProject/react-examples) repository and create a Pull Request there. When approved, the example will eventually be uploaded to CodeSandbox. In the meantime, leave a placeholder in the lesson file like so:

```
// some lesson content

**EXAMPLE GOES HERE**

// some lesson content

```

**Comment by kmsedu** [comment]
I'd love to tackle this 👍
