### ISSUE TITLE
Lesson: React Components

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#222]
## Lesson: React Components

**Section: Getting Started With React**

#196 

----

## Lesson Overview

Introduction to React components, what they do, and how to write them

## Lesson Outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Explain that User Interfaces (UI) can be broken down into reusable chunks (components), this is where React shines.
- Ask users to use the project the set up in the [Setting Up A React Environment lesson](https://github.com/TheOdinProject/top-meta/issues/221) as reference for this lesson. By the end of the lesson, encourage learners to write a couple more.
- Briefly go over a component’s structure: their names should be capitalised, they return JSX, and they normally live in their own dedicated files. Touch on how to import/export components (components normally get exported as defaults).
- The [Components section of the current React Introduction lesson](https://www.theodinproject.com/lessons/node-path-javascript-react-introduction#components) can be used as a reference.

## Acceptance Criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get The Lesson Template

Download the lesson template using the following command (replace lesson_name with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

### Adding Interactive Examples

We'll use [CodeSandbox](https://codesandbox.io/dashboard) for interactive examples. To add these examples, follow the instructions in the [react-examples](https://github.com/TheOdinProject/react-examples) repository and create a Pull Request there. When approved, the example will eventually be uploaded to CodeSandbox. In the meantime, leave a placeholder in the lesson file like so:

```
// some lesson content

**EXAMPLE GOES HERE**

// some lesson content

```

**Comment by mgrigoriev8109** [comment]
I'd like to tackle this one 🗡

**Comment by 01zulfi** [comment]
Completed with https://github.com/TheOdinProject/curriculum/pull/24702
