### ISSUE TITLE
Chore: Remove The Floating Chat Bubble

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/top-meta#224]
**Because:**
We don't need this component anymore.

**Action:**
Remove the floating chat bubble from the app:

<img width="224" alt="Screenshot 2022-08-24 at 08 57 33" src="https://user-images.githubusercontent.com/7963776/186363449-dae1391f-3179-4e1e-81f8-45f92f2278b8.png">

**Comment by bscottnz** [comment]
🙋
