### ISSUE TITLE
Lesson: What is JSX?

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#226]
## Lesson: What is JSX?

**Section: Getting Started With React**

#196 

----

## Lesson Overview

All about JSX

## Lesson Outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Explain JSX i.e it is a syntax extension for JavaScript that basically allows writing HTML like code in JavaScript. Prompt learners to console.log JSX elements to show that JSX compiles down to React. Make a case that JSX isn’t required to write React components, although it simplifies the process.
- Touch on basic syntax for JSX to allow learners to get familiar with JSX. This should allow them to understand any JSX code snippet that comes up in later lessons.

## Acceptance Criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get The Lesson Template

Download the lesson template using the following command (replace lesson_name with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

### Adding Interactive Examples

We'll use [CodeSandbox](https://codesandbox.io/dashboard) for interactive examples. To add these examples, follow the instructions in the [react-examples](https://github.com/TheOdinProject/react-examples) repository and create a Pull Request there. When approved, the example will eventually be uploaded to CodeSandbox. In the meantime, leave a placeholder in the lesson file like so:

```
// some lesson content

**EXAMPLE GOES HERE**

// some lesson content

```

**Comment by Aureatus** [comment]
Hey, i'd like to take this lesson.
