### ISSUE TITLE
Lesson: Component Lifecycle Methods

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#231]
## Lesson: Component Lifecycle Methods

**Section: Class Components**

#198 

----

## Lesson Overview

A lesson on lifecycle methods; a component mounts, updates, and unmounts.

## Lesson Outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- From the previous sections, the learner should have an idea of a component’s lifecycle even if it isn’t covered explicitly. In class based components, there are special methods called lifecycle methods. Give a brief overview of the important few and allow learners to research on their own.

## Acceptance Criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get The Lesson Template

Download the lesson template using the following command (replace lesson_name with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

### Adding Interactive Examples

We'll use [CodeSandbox](https://codesandbox.io/dashboard) for interactive examples. To add these examples, follow the instructions in the [react-examples](https://github.com/TheOdinProject/react-examples) repository and create a Pull Request there. When approved, the example will eventually be uploaded to CodeSandbox. In the meantime, leave a placeholder in the lesson file like so:

```
// some lesson content

**EXAMPLE GOES HERE**

// some lesson content

```

**Comment by Aureatus** [comment]
Hey, i'd like to take this lesson.

**Comment by Aureatus** [comment]
@01zulfi Regarding the lifecycle methods, should I include a section on the lifecycle itself, or will that have been covered sufficiently in the states and effects section?

**Comment by 01zulfi** [comment]
@Aureatus  My instincts say we won't need to. Just couple of sentences in the introduction of the lesson should suffice.

**Comment by 01zulfi** [comment]
@Aureatus I don't have any preference. Let's go with what you prefer.
