### ISSUE TITLE
Lesson: React Router

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#253]
## Lesson: React Router

**Section: React Ecosystem**

#200 

----

## Lesson Overview

This lesson covers routing and related concepts using the React Router library.

## Lesson Outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Delve into the rise of client-side routing with SPAs. 
- Introduce React Router as an excellent solution for React. 
- Walkthrough how to incorporate React Router in an application, i.e using `createBrowserRouter` & `RouterProvider` etc
- Explain concepts of protected routes and nested routes with examples

*** LESSON OUTLINE STILL IN DISCUSSION ***

## Acceptance Criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get The Lesson Template

Download the lesson template using the following command (replace lesson_name with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

### Adding Interactive Examples

We'll use [CodeSandbox](https://codesandbox.io/dashboard) for interactive examples. To add these examples, follow the instructions in the [react-examples](https://github.com/TheOdinProject/react-examples) repository and create a Pull Request there. When approved, the example will eventually be uploaded to CodeSandbox. In the meantime, leave a placeholder in the lesson file like so:

```
// some lesson content

**EXAMPLE GOES HERE**

// some lesson content

```

**Comment by Lofty-Brambles** [comment]
@01zulfi I'd like to work on this :)
