### ISSUE TITLE
Lesson: Project CV Application

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#265]
## Lesson: Project CV Application

**Section: States And Effects**

#197 

----

## Lesson Overview

Project CV Application to practice React concept the learners have learned so far.

## Lesson Outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Use the current project as reference: https://www.theodinproject.com/lessons/node-path-javascript-cv-application
- Remove "A quick reminder" section
- Remove CRA specific instructions
- Remove GitHub Pages instructions
- Remove class components instructions
- Add section called "Deploying a React App" 
    - This section should introduce [Netlify](https://www.netlify.com/) and [Vercel](https://vercel.com/home) as hosting options
    - Link to specific docs to deploy their React App for both platforms
    - If there's any other platform that makes sense to include, please include them.

## Acceptance Criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get The Lesson Template

Download the lesson template using the following command (replace lesson_name with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

### Adding Interactive Examples

We'll use [CodeSandbox](https://codesandbox.io/dashboard) for interactive examples. To add these examples, follow the instructions in the [react-examples](https://github.com/TheOdinProject/react-examples) repository and create a Pull Request there. When approved, the example will eventually be uploaded to CodeSandbox. In the meantime, leave a placeholder in the lesson file like so:

```
// some lesson content

**EXAMPLE GOES HERE**

// some lesson content

```

**Comment by CouchofTomato** [comment]
@01zulfi Can you confirm on ^^ please mate.

**Comment by 01zulfi** [comment]
@Lofty-Brambles Assigned
