### ISSUE TITLE
Lesson: Project Shopping Cart

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#267]
## Lesson: Project Shopping Cart

**Section: The React Ecosystem**

#200 

----

## Lesson Overview

Shopping Cart project for learners to practice React

## Lesson Outline

The following items define the scope of the lesson. The lesson outline is flexible; you can improve, expand, and omit items whilst writing lesson content (make sure the pull request description mentions that).

- Use https://www.theodinproject.com/lessons/node-path-javascript-shopping-cart as a reference
- Remove CRA instruction
- Add fetching from an API a project requirement
- Remove GitHub pages specific instructions
- Check whether there's an additional step when deploying a React app with client side routing to Netlify and Vercel. Add those instructions.

## Acceptance Criteria

If the requirements here are not met, the work effort is not complete.

- [ ] Lesson conforms to the outline above (unless outline has been modified).
- [ ] Lesson follows our [Layout Style Guide](https://github.com/TheOdinProject/curriculum/blob/main/LAYOUT_STYLE_GUIDE.md).

### Get The Lesson Template

Download the lesson template using the following command (replace lesson_name with the actual lesson name):

```bash
curl -o <lesson_name>.md https://raw.githubusercontent.com/TheOdinProject/curriculum/main/templates/lesson-template.md 
```

### Adding Interactive Examples

We'll use [CodeSandbox](https://codesandbox.io/dashboard) for interactive examples. To add these examples, follow the instructions in the [react-examples](https://github.com/TheOdinProject/react-examples) repository and create a Pull Request there. When approved, the example will eventually be uploaded to CodeSandbox. In the meantime, leave a placeholder in the lesson file like so:

```
// some lesson content

**EXAMPLE GOES HERE**

// some lesson content

```

**Comment by Lofty-Brambles** [comment]
Since I asked for the other projects, could this be assigned to me too?

**Comment by CouchofTomato** [comment]
@01zulfi ^^
