### ISSUE TITLE
Add a Conclusion lesson to the JavaScript course

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/top-meta#282]
The current conclusion lesson https://www.theodinproject.com/lessons/node-path-javascript-conclusion will become outdated, we'll need to update that lesson, or write a new one for the JavaScript course.

**Comment by nguyenlekhtn** [comment]
What will be outdated? I looked at that lesson and I think the words in there are very general and won't need  to change

**Comment by 01zulfi** [comment]
The new React lessons will be put into a separate new course after the current JavaScript course. I agree, not all parts of the lessons will be outdated, though some of it will be. For example, the selected text here would be outdated when the new React course drops:

![image](https://github.com/TheOdinProject/top-meta/assets/85733202/95303610-0408-4dbe-9af0-3f458b98d2fb)
