### ISSUE TITLE
Feature: Team Page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/top-meta#3]
| Title | Author | Date |
| --- | --- | --- |
| Team Page | Kevin | 27/07/2021 |

# Team Page

## Summary

A page on the site that will provide details about the team behind TOP.

## Motivation

* It will help give credibility to the platform by being transparent about the team behind the project.
* It will help give credibility to the curriculum as it will show the project is being run by a team with industry experience.
* It will provide a place where we can be transparent about the process of becoming a maintainer so anyone interesting in joining the team can find out what they need to do.
* It could potentially be used to highlight the roles and skill gaps we need filled within the team. 
* Replaces the [out of date hall of fame section](https://www.theodinproject.com/contributing) on the contributing page to give deserved recognition to the volunteers behind TOP.

## Suggested implementation

A standard team page like the [templates here](https://tailwindui.com/components/marketing/sections/team-sections) would do.

Each team member would have an avatar, a brief description and possible social links. We could include how long they've been working in the industry and/or TOP and what they've mostly worked on with TOP.

Splitting the page into two sections for the current team and past team members would be good for giving recognition to past team members who have helped make TOP what is is and fulfil the same purpose as the current HOF section does.

## Drawbacks

* Potential for doxing team members who would rather remain private. We shouldn't have any requirements for anyone listed on the team page to use a real avatar of themselves or to provide personal details about where they work or social links if they'd rather not include any of those.

## Alternatives

We could update the [HOF on the contributing page](https://www.theodinproject.com/contributing) instead.

## Additional

Most team members have naturally fallen into different roles. But we haven't formally discussed it. It may be a good idea to formally agree on roles if we are want to include that information about each team member. 

**Examples**
[Ruby on Rails team page](https://rubyonrails.org/community)
I like how they list the country of each maintainer and how long they've been part of the team. It shows they are from a wide range of cultures and the project has stability with longer serving members while also growing with members joining more recently.
<img width="1053" alt="Screenshot 2022-10-30 at 12 41 10" src="https://user-images.githubusercontent.com/7963776/198878985-4d4b79f1-f29d-4292-b7b1-9c8f595598b3.png">

[Crystal Lang Team](https://crystal-lang.org/team/)
I like the alumni section and the part about all the other contributors not part of the team - giving recognition to everyone past and present.
<img width="1188" alt="Screenshot 2022-10-30 at 12 43 02" src="https://user-images.githubusercontent.com/7963776/198879158-c0b13453-b20b-48ec-b43f-a1ffb7fb56c0.png">

**Comment by kashura** [comment]
@KevinMulhern i might have missed this, but do we have an action plan for this or is it just an idea at this point?

**Comment by KevinMulhern** [comment]
@kashura Yeah it's just an idea for the funnel at this point mate.
