### ISSUE TITLE
Lesson: HTML/CSS - Advanced Selectors

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/top-meta#31]
# Lesson Overview
covers all the fancy selectors that we didn't get to in foundations

# Lesson Outline
The _order_ of this outline doesn't need to be followed 100%, but the items listed here _do_ need to show up in the lesson somewhere. If you feel like there has been an omission ask in Discord before expanding the scope of this lesson.

[this document](https://websitesetup.org/wp-content/uploads/2019/11/wsu-css-cheat-sheet-gdocs.pdf) has a good list on page 20 and 23

feel free to find an external resource to cover them.

- parent/sibling
- Attribute
- Pseudo-selectors
  - Hover, focus, before/after, first/last-child etc.

# Acceptance Criteria
This is the definition of success. If the requirements here are not met, the work effort is not complete.
- [ ] All items from the outline above are present in the lesson.
- [ ] Lesson follows proper format
  - [ ] Section headings are `###`
  - [ ] Code blocks use `~~~` and include a language name.
  - [ ] Lists are numbered.
- [ ] Lesson has the following sections:
  - [ ] 'Learning Outcomes' at the beginning, optionally after a short introduction paragraph (relatively brief, give students an overview of what they're about to learn, with few specific details)
  - [ ] Assignment(optional) a list of resources to consume.
  - [ ] Practice(optional) 
  - [ ] 'Additional Resources' (should exist even if it's blank)
  - [ ] 'Knowledge Check' (specific questions to test knowledge. Has details. Doesn't just parrot the Learning Outcomes. More of a spot-check, doesn't need to be exhaustive)
- [ ] Lesson has been run through a spell-checker

**Comment by ChargrilledChook** [comment]
Hey, I'd like to give this one a go if possible!

**Comment by codyloyd** [comment]
it's yours!  please move this into the 'in progress' column when you start working on it.

check this issue to get a feel for what students should already know https://github.com/TheOdinProject/top-meta/issues/19

**Comment by ChargrilledChook** [comment]
I don't have permission to move cards on the project board, but I've made a start

**Comment by ChargrilledChook** [comment]
PR here: https://github.com/TheOdinProject/curriculum/pull/22699
