### ISSUE TITLE
Lesson: Html/css - SVG

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/top-meta#43]
# Lesson Overview
We need a lesson that covers svg!

# Lesson Outline
The _order_ of this outline doesn't need to be followed 100%, but the items listed here _do_ need to show up in the lesson somewhere. If you feel like there has been an omission ask in Discord before expanding the scope of this lesson.

- Benefits of SVG over other graphics formats.
- basic format/syntax
  - be sure to note that nobody actually codes these by hand.  Not uncommon for people to _edit_ the code as needed, but nobody is drawing complex shapes by writing svg code.
 - basic usage (inline/imported)
 - sources for svg icons/images

# Acceptance Criteria
This is the definition of success. If the requirements here are not met, the work effort is not complete.
- [ ] All items from the outline above are present in the lesson.
- [ ] Lesson follows proper format
  - [ ] Section headings are `###`
  - [ ] Code blocks use `~~~` and include a language name.
  - [ ] Lists are numbered.
- [ ] Lesson has the following sections:
  - [ ] 'Learning Outcomes' at the beginning, optionally after a short introduction paragraph (relatively brief, give students an overview of what they're about to learn, with few specific details)
  - [ ] Assignment(optional) a list of resources to consume.
  - [ ] Practice(optional) 
  - [ ] 'Additional Resources' (should exist even if it's blank)
  - [ ] 'Knowledge Check' (specific questions to test knowledge. Has details. Doesn't just parrot the Learning Outcomes. More of a spot-check, doesn't need to be exhaustive)
- [ ] Lesson has been run through a spell-checker

**Comment by isaiahaiasi** [comment]
Commenting to get assigned. Excited to get started on this! 😁
