### ISSUE TITLE
Git Branching Basics Lesson

### ISSUE THREAD

**Issue by wise-king-sullyman** [TheOdinProject/top-meta#46]
# Overview
We need a lesson (or addition to an existing lesson) that explains the basics of branching to students. It should undo some of what was done in [this PR](https://github.com/TheOdinProject/curriculum/pull/22320) and equip learners with the skills needed to use branching on the UI building portion of RPS. This lesson should be located immediately before (or as part of) the revisiting RPS project in foundations.

## Acceptance Criteria

- [x] The fork and branch resource added in [this PR](https://github.com/TheOdinProject/curriculum/pull/22320) is removed and all links pointing back to it in future lessons are also removed/updated to coincide with the new content
- [x] Content informs students on (the basics of) what branches are (i.e. they aren't folders)
- [x] Content explains basic commands/workflow to branch (i.e. how to make a branch, switch branches, merge)
~~- [ ] Content explains what a merge conflict is, and how to resolve a basic merge conflict~~

**Comment by zachmmeyer** [comment]
Commenting
