### ISSUE TITLE
Official TOP Blog

### ISSUE THREAD

**Issue by twalton83** [TheOdinProject/top-meta#49]
It has been requested that we consider adding an official Odin blog where core/maintainers can write about non curriculum content.

**Comment by twalton83** [comment]
I think in the context of wanting to grow presence, Medium and Dev.to are necessary. But I do believe having an inhouse blog is helpful.

**Comment by rlmoser99** [comment]
To be more specific, some of the material would be good for a blog post, like general tips of learning programming, how to break down a problem, etc. But posts that are very specific to TOP and/or our Discord community, I would really like to keep within the confines of TOP & be open-source.

**Comment by twalton83** [comment]
Done by way of Dev.to.
