### ISSUE TITLE
Lesson: HTML/CSS - Floats

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/top-meta#54]
# Lesson Overview
Floats are a little bit old-fashioned.. but they have their place and deserve a mention.  This lesson can be pretty short.

# Lesson Outline
The _order_ of this outline doesn't need to be followed 100%, but the items listed here _do_ need to show up in the lesson somewhere. If you feel like there has been an omission ask in Discord before expanding the scope of this lesson.

  - feel free to _discuss_ the fact that floats were used for layout back in the day... but stray FAR away from actually recommending them for anything besides sticking inline elements inside a paragraph. 
  - floats remove content from the normal document flow!
  - cover shapes with `shape-outside`, and the chrome shape-editor.  Pretty niche behavior.. but it's neat and worth mentioning.

# Acceptance Criteria
This is the definition of success. If the requirements here are not met, the work effort is not complete.
- [ ] All items from the outline above are present in the lesson.
- [ ] Lesson follows proper format
  - [ ] Section headings are `###`
  - [ ] Code blocks use `~~~` and include a language name.
  - [ ] Lists are numbered.
- [ ] Lesson has the following sections:
  - [ ] 'Learning Outcomes' at the beginning, optionally after a short introduction paragraph (relatively brief, give students an overview of what they're about to learn, with few specific details)
  - [ ] Assignment(optional) a list of resources to consume.
  - [ ] Practice(optional) 
  - [ ] 'Additional Resources' (should exist even if it's blank)
  - [ ] 'Knowledge Check' (specific questions to test knowledge. Has details. Doesn't just parrot the Learning Outcomes. More of a spot-check, doesn't need to be exhaustive)
- [ ] Lesson has been run through a spell-checker

**Comment by mgrigoriev8109** [comment]
I’d like to do this one.

**Comment by mgrigoriev8109** [comment]
discord name: mikhail
