### ISSUE TITLE
Lesson: HTML/CSS - Emmet

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/top-meta#56]
# Lesson Overview
This one is unique because it's basically just an editor tip... but emmet is _incredible_ so I think we should include it... it's a real life-saver for someone that edits a bunch of html/css

# Lesson Outline
The _order_ of this outline doesn't need to be followed 100%, but the items listed here _do_ need to show up in the lesson somewhere. If you feel like there has been an omission ask in Discord before expanding the scope of this lesson.

- what it is
- how to trigger it
- the basic expansions (https://docs.emmet.io/cheat-sheet/)
- some of the more useful expanded functions (wrap with abbreviation, remove tag)
  - how to set up KB shortcuts for these in vscode 😎 
- link to the docs so people can dig around and experiment.
  
  ![](https://media1.giphy.com/media/KXY5lB8yOarLy/giphy.gif?cid=7896f6a6zntqn7fr8k2e11zdybd6kt6gf7228iin7iuyakou&rid=giphy.gif&ct=g) 

# Acceptance Criteria
This is the definition of success. If the requirements here are not met, the work effort is not complete.
- [ ] All items from the outline above are present in the lesson.
- [ ] Lesson follows proper format
  - [ ] Section headings are `###`
  - [ ] Code blocks use `~~~` and include a language name.
  - [ ] Lists are numbered.
- [ ] Lesson has the following sections:
  - [ ] 'Learning Outcomes' at the beginning, optionally after a short introduction paragraph (relatively brief, give students an overview of what they're about to learn, with few specific details)
  - [ ] Assignment(optional) a list of resources to consume.
  - [ ] Practice(optional) 
  - [ ] 'Additional Resources' (should exist even if it's blank)
  - [ ] 'Knowledge Check' (specific questions to test knowledge. Has details. Doesn't just parrot the Learning Outcomes. More of a spot-check, doesn't need to be exhaustive)
- [ ] Lesson has been run through a spell-checker

**Comment by Ishmam156** [comment]
Hey Cody!

Since no one has grabbed this yet, I would like to take this on :)

**Comment by LeoKirasic** [comment]
Considering @Ishmam156 doesn't have the time to take this on, I'll be jumping in. @codyloyd
