### ISSUE TITLE
Data Structures & Algorithms Course

### ISSUE THREAD

**Issue by marvingay** [TheOdinProject/top-meta#58]
# Data Structures & Algorithms Course

## Summary

Develop a comprehensive, language agnostic course that covers the data structures and common algorithms necessary to cover the breadth needed to solve interview questions and to expand understanding on the underlying implementations of real-world problems and other technologies.

## Motivation

In the face of not having parity between the Rails and NodeJS Paths, the long-term goal is to have a common course shared between the paths to accommodate this highly requested item.

## Suggested implementation

Present topics in a linear fashion as more advanced algorithms and data structures rely on conceptual understanding of more fundamental topics. Each structure or algorithm specific lesson will be accompanied by any or all of the following assignments: 

1. Implementation in preferred language.
2. Practice problems related to or concerning the use the particular topic
3. Practical real world example.

Proposed list of lesson coverage (order is subject to change):
- Introduction
- Time Complexity (Big O analysis of algorithms)
- Recursion (What it is, how to apply, famous problems)
- Arrays (comprehensive review)
- Multi-dimensional Arrays (matrix/array of arrays)
- Searching (Linear Search, Binary Search)
- Sorting (Bubble Sort, Merge Sort, Quick Sort, maybe more.... common patterns)
- Sliding Window technique
- Sets, Hashing
- Strings (no clue what to cover here in an agnostic manner)
- Linked List (implementation, common problems)
- Stack, Queue, Deque
- Tree / Binary Search Tree
- Graphs (implementation/representation as adjacency list/matrix)
- Breadth First Search
- Depth First Search
- Cycle detection
- Shortest Paths (Djikstra's, Bellman Ford)
- Greedy Algorithms (famous problems)
- Backtracking (famous problems)
- Dynamic Programming (famous problems)

Advanced Stuff (nice to have):
- Strongly Connected Components (Graphs)
- Trie data structure (Strings)
- Disjoint Set
- Segment Trees
- Any Math stuff
- Bit Manipulation
- Convex Hull

## Drawbacks

Are there any drawbacks to this proposal? consider the following:
- Time consuming
- 2-3 month appetite for completion (as a solo effort).f

## Alternatives
N/A - can be explored.

## Additional

Course placement.
Scope of practice

**Comment by mgrigoriev8109** [comment]
I'd like to work on this.

**Comment by twentysixhugs** [comment]
Can I please find out how the work is going? Really anticipating the course :)
