### ISSUE TITLE
Advanced Git Topics Lesson

### ISSUE THREAD

**Issue by wise-king-sullyman** [TheOdinProject/top-meta#62]
# Overview
We need a lesson that explains a bit about how Git works "under the hood" and explains some more advanced Git topics like changing history.  It should be added to both the Ruby and JS courses and placed somewhere around Battleship in the JS course and Connect Four in the Ruby course.

It can be largely based on [this lesson](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/a-deeper-look-at-git) which is currently in the Git section of the Ruby course. The PR addressing this issue should add these new lessons in this new location, and remove the "A Deeper Look at Git" lesson linked here.

## Acceptance Criteria

- [ ] [This lesson](https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-programming/lessons/a-deeper-look-at-git) is removed from the Git section of Ruby, and the Git section of the Ruby course is itself removed if this was that last lesson in it.
- [ ] Content explains the different ways that commit history can be changed, and how to work with remotes when changing history
- [ ] Content explains clearly that some history-changing operations can be risky, highlights their danger, and points out best practices with history changing (i.e. don't do it on a team project without making sure it's ok to do, and others know you're doing it)
- [ ] Content explains that Git branches are really just pointers, and what that means. Some care should be taken here to ensure the pointer explanation is adequate because the "A Deeper Look at Git" lesson has been only in the Ruby course so far and Odinites have pointed out in the past that the linked list and BST lessons helped prepare them to understand pointers. Those on the JavaScript track will not have done these projects.

**Comment by mgrigoriev8109** [comment]
@mikhail here.
