### ISSUE TITLE
Git Basics Changes

### ISSUE THREAD

**Issue by wise-king-sullyman** [TheOdinProject/top-meta#64]
# Overview
We need to make changes to the Git Basis lesson to incorporate items from the braindump (#47) specifying that they should be added to this lesson.

 

## Acceptance Criteria

- [ ] The difference between cloning and adding a remote (and when each should be done) is specified
- [ ] Content specifies that a `repos` directory should be made within the user's home directory, and that projects should be cloned into this directory or initialized from a directory within the `repos` directory
- [ ] Assignment is reworked as needed to have students initialize the `git_test` repo with a README
- [ ] Assignment still provides the same level of experience with using Git

**Comment by zachmmeyer** [comment]
Comment
