### ISSUE TITLE
Lesson: DSA - Recursion

### ISSUE THREAD

**Issue by marvingay** [TheOdinProject/top-meta#84]
# Lesson Overview
This lesson will explain what Recursion is, why it's used, and the time and space complexity implications of using recursion.

# Lesson Outline
This lesson will be a revision of the already existing [Recursive Methods lesson](https://github.com/TheOdinProject/curriculum/blob/main/ruby_programming/computer_science/lesson_recursion.md).

1. Provide an in-lesson, text explanation of Recursion (additionally, what makes a function recursive in implementation)
2. Create an assignment (for resource consumption) that contains **one** video and **one article**.
3. Expand on the difference between iteration and recursion (additionally, space complexity trade-off)
4. Expand on Practicality of using Recursion in Interview Questions and Programming Problems

# Acceptance Criteria
This is the definition of success. If the requirements here are not met, the work effort is not complete.
- [ ] All items from the outline above are present in the lesson.
- [ ] Lesson follows proper format
  - [ ] Section headings are `###`
  - [ ] Code blocks use `~~~` and include a language name.
  - [ ] Lists are numbered.
- [ ] Lesson has the following sections:
  - [ ] 'Learning Outcomes' at the beginning, optionally after a short introduction paragraph (relatively brief, give students an overview of what they're about to learn, with few specific details)
  - [ ] Assignment(optional) a list of resources to consume.
  - [ ] Practice(optional) 
  - [ ] 'Additional Resources' (should exist even if it's blank)
  - [ ] 'Knowledge Check' (specific questions to test knowledge. Has details. Doesn't just parrot the Learning Outcomes. More of a spot-check, doesn't need to be exhaustive)
- [ ] Lesson has been run through a spell-checker

**Comment by TaylorJonesTRT** [comment]
I'd like to take this on!
