### ISSUE TITLE
Chore: Convert Login Page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/top-meta#92]
Because:
We are upgrading CSS to Tailwind

Action:
Convert the sign up page to use tailwind styles

**Note:** Form fields have already been done in this PR: https://github.com/TheOdinProject/theodinproject/pull/3299

Acceptance Criteria:

- [x] The page is styled with Tailwind
- [x] There are no regressions in features

**Comment by bscottnz** [comment]
Can I take this?
